In [81]:
import pandas as pd

In [82]:
df_test = pd.read_csv(r"drive/MyDrive/bnp_dataset/X_test_8skS2ey.csv",low_memory=False)

In [83]:
df_train = pd.read_csv(r"drive/MyDrive/bnp_dataset/X_train_G3tdtEn.csv",low_memory=False)

In [84]:
y_train = pd.read_csv(r"/content/drive/MyDrive/bnp_dataset/Y_train_2_XPXJDyy.csv")

In [85]:
item_unique = []
for i in range(1,25):
 item_unique += df_train.fillna("")[f"item{i}"].unique().tolist()
 item_unique += df_test.fillna("")[f"item{i}"].unique().tolist()
item_unique = set(item_unique)
item_unique.discard("")
len(item_unique)

177

Nombre de cat√©gorie de produits : 177

In [86]:
make_unique = []
for i in range(1,25):
 make_unique += df_train.fillna("")[f"make{i}"].unique().tolist()
 make_unique += df_test.fillna("")[f"make{i}"].unique().tolist()
make_unique = set(make_unique)
make_unique.discard("")
len(make_unique)

887

Nombre de marques : 887

In [87]:
df_item = pd.DataFrame(columns=item_unique,index=df_train.index)

In [88]:
for row in df_train.index:
    for i in range(1,25):
        if type(df_train[f"item{i}"][row]) == float: # Stop si valeur nulle
            break
        df_item[f"{df_train[f'item{i}'][row]}"][row] = df_train[f"Nbr_of_prod_purchas{i}"][row]

In [89]:
df_make = pd.DataFrame(columns=make_unique,index=df_train.index)

In [90]:
for row in df_train.index:
    for i in range(1,25):
        if type(df_train[f"make{i}"][row]) == float: # Stop si valeur nulle
            break
        df_make[f"{df_train[f'make{i}'][row]}"][row] = df_train[f"Nbr_of_prod_purchas{i}"][row]

In [91]:
result = pd.concat([df_make, df_item], axis=1)

In [92]:
for i in range(1,25):
  result[f'cash_price{i}'] = df_train[f'cash_price{i}']
  result[f'Nbr_of_prod_purchas{i}'] = df_train[f'Nbr_of_prod_purchas{i}']

In [93]:
result['Nb_of_items'] = df_train['Nb_of_items']

In [94]:
result = result.fillna(0)

In [95]:
result["fraud_flag"] = y_train["fraud_flag"]

<ipython-input-95-bf96564583d7>:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  result["fraud_flag"] = y_train["fraud_flag"]

In [96]:
result

,BUGABOO,BRAUN,FALKE,THEIR NIBS,THE LITTLE BOTANICAL,SWYFT,TOTTER + TUMBLE,LEON,TERENCE CONRAN,GINGER FOX,...,cash_price21,Nbr_of_prod_purchas21,cash_price22,Nbr_of_prod_purchas22,cash_price23,Nbr_of_prod_purchas23,cash_price24,Nbr_of_prod_purchas24,Nb_of_items,fraud_flag
0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
1,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
2,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
3,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0
4,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92785,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0
92786,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
92787,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0
92788,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0
92789,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0

In [97]:
df_fraud_by_20 = pd.concat([result[result["fraud_flag"]==1] for i in range(10)],axis=0)
df2 = pd.concat([df_fraud_by_20,result[result["fraud_flag"]==0]],axis=0)

In [98]:
X = result.drop("fraud_flag",axis=1).values
y = result["fraud_flag"].values

In [99]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=42)
clf.fit(X,y)

RandomForestClassifier(random_state=42)

In [100]:
df_test = pd.read_csv(r"drive/MyDrive/bnp_dataset/X_test_8skS2ey.csv",low_memory=False)

In [101]:
y_test = pd.read_csv(r"/content/drive/MyDrive/bnp_dataset/Y_test_random_2.csv")

In [102]:
df_item_test = pd.DataFrame(columns=item_unique,index=df_test.index)
df_make_test = pd.DataFrame(columns=make_unique,index=df_test.index)

In [103]:
for row in df_test.index:
    for i in range(1,25):
        if type(df_test[f"item{i}"][row]) == float: # Stop si valeur nulle
            break
        try:
          df_item_test[f"{df_test[f'item{i}'][row]}"][row] = df_test[f"Nbr_of_prod_purchas{i}"][row]
        except:
          pass

In [104]:
for row in df_test.index:
    for i in range(1,25):
        if type(df_test[f"make{i}"][row]) == float: # Stop si valeur nulle
            break
        try:
          df_make_test[f"{df_test[f'make{i}'][row]}"][row] = df_test[f"Nbr_of_prod_purchas{i}"][row]
        except:
          pass

In [105]:
result_test = pd.concat([df_make_test, df_item_test], axis=1)
for i in range(1,25):
  result_test[f'cash_price{i}'] = df_test[f'cash_price{i}']
  result_test[f'Nbr_of_prod_purchas{i}'] = df_test[f'Nbr_of_prod_purchas{i}']
result_test['Nb_of_items'] = df_test['Nb_of_items']

In [106]:
result_test = result_test.fillna(0)

In [107]:
result_test.to_csv(r"/content/drive/MyDrive/bnp_dataset/X_test_item_make.csv",index=False)

In [108]:
resultat = pd.DataFrame(clf.predict_proba(result_test.values))

In [109]:
resultat = resultat.rename({1:"fraud_flag"},axis=1)

In [110]:
resultat = resultat.drop(0,axis=1)

In [111]:
resultat["ID"] = df_test["ID"]

In [112]:
resultat = resultat[["ID","fraud_flag"]]

In [113]:
resultat.to_csv("drive/MyDrive/data/2_test.csv")

In [114]:
resultat

           ID  fraud_flag
0       64707    0.000000
1       63919    0.000000
2       15664    0.000000
3        6626    0.107612
4       26766    0.064031
...       ...         ...
23193   63474    0.000000
23194   80438    0.000000
23195   29485    0.022451
23196   59838    0.000000
23197  110584    0.028694

[23198 rows x 2 columns]

In [115]:
y_test

       index      ID  fraud_flag
0          0   64707    0.165105
1          1   63919    0.284590
2          2   15664    0.497070
3          3    6626    0.491428
4          4   26766    0.994971
...      ...     ...         ...
23193  23193   63474    0.983022
23194  23194   80438    0.705398
23195  23195   29485    0.689810
23196  23196   59838    0.882254
23197  23197  110584    0.425888

[23198 rows x 3 columns]